server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5431/order-service
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  kafka:
    bootstrap-servers: broker:29092

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
