eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # not a client
    fetch-registry: false # not a client, only client saved registry
  username: ${EUREKA_USERNAME:eureka}
  password: ${EIREKA_PASSWORD:password}


server:
  port: 8761

