eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # not a client
    fetch-registry: false # not a client, only client saved registry
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}


server:
  port: 8761


management:
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
