spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/product-service




eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8080