server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/inventory-service
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka